# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: pgatk
channels:
  - openms
  - conda-forge
  - bioconda
dependencies:
  - biopython
  - Click
  - gffutils
  - numpy
  - PyYAML
  - requests
  - simplejson
  - ratelimit
  - bioconda::pyteomics
  - pybedtools
  - matplotlib
  - bioconda::pyopenms
  - pytest
  - tqdm
  - pyahocorasick
