site_name: PGATK - ProteoGenomics Analysis ToolKit
site_description: Python tools for proteogenomics data analysis
site_author: BigBio Team

site_url: https://pgatk.quantms.org/

repo_name: bigbio/pgatk
repo_url: https://github.com/bigbio/pgatk

theme:
  name: material
  font: false
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_css:
  - stylesheets/pgatk-theme.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - def_list
  - tables
  - footnotes
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
      toc_depth: 3

plugins:
  - search:
      lang:
        - en

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - pgatk CLI: pgatk-cli.md
  - File Formats: formats.md
  - Changelog: changelog.md
  - Support: support.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bigbio/pgatk
      name: GitHub Repository
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pgatk/
      name: PyPI Package

copyright: Copyright &copy; 2020-2026 BigBio Team
