Experiment	Peptide	PSMs	Quant
Bonobo	SLFWYVQYPGEGLQL	1	1
Bonobo	YYKTIEELRDKILT	1	1
Bonobo	RIVVDEVYDYHQGTYVCDD	1	1
Bonobo	GNASEVSVACLTERIHQMEENQ	1	1
Bonobo	QDWRQAYHYANLL	1	1
Bonobo	EDSKPITLDTTDF	1	1
Bonobo	ECLEEGFEPPTGMDCPTISCD	1	1
