"""HGVS compliance tests for get_mut_pro_seq across all SO variant types.

Each test uses a real mutation from Cosmic_CompleteTargetedScreensMutant_v103_GRCh38.tsv
paired with the matching CDS from Cosmic_Genes_v103_GRCh38.fasta.

HGVS rules verified per type:
  missense_variant        – single AA substitution, length unchanged
  stop_gained             – stop (*) introduced at predicted position
  inframe_deletion        – protein shortened by exact number of deleted codons
  inframe_insertion       – protein lengthened by exact number of inserted codons (dup)
  protein_altering_variant– delins produces a non-empty altered sequence
  frameshift_variant      – out-of-frame deletion produces a non-empty translated sequence
  start_lost              – start codon destroyed; first AA is no longer Met
  stop_lost               – stop codon removed; protein extends past original terminus
  stop_retained_variant   – stop codon changed but still a stop; length unchanged
  synonymous_variant      – filtered before get_mut_pro_seq (pre-processing step)
  intron_variant          – p.? guard returns empty string
  3_prime_UTR_variant     – p.? guard returns empty string
  5_prime_UTR_variant     – p.? guard returns empty string
  coding_sequence_variant – p.? guard returns empty string
  splice_acceptor_variant – p.? guard returns empty string
  splice_donor_variant    – intronic offset guard returns empty string
  splice_region_variant   – treated as missense when combined type contains missense_variant
  incomplete_terminal_codon_variant – not present in v103 targeted screens; p.? returns ""
"""
from Bio.Seq import Seq

from pgatk.cgenomes.cgenomes_proteindb import CancerGenomesService
from pgatk.cgenomes.models import SNP

# ---------------------------------------------------------------------------
# CDS sequences from Cosmic_Genes_v103_GRCh38.fasta
# Key: gene symbol  Value: CDS nucleotide string (ENST accession in comment)
# ---------------------------------------------------------------------------
_CDS = {
    # ENST00000483967.5 – used for missense_variant
    "EZH2": (
        "ATGGGCCAGACTGGGAAGAAATCTGAGAAGGGACCAGTTTGTTGGCGGAAGCGTGTAAAATCAGAGTACATGCGACTGAGACAGCTCAAGAGGTTCAGACGAGCTGATGAAGTAAAGAGTATGTTTAGTTCCAATCGTCAGAAAATTTTGGAAAGAACGGAAATCTTAAACCAAGAATGGAAACAGCGAAGGATACAGCCTGTGCACATCCTGACTTCTTGTTCGGTGACCAGTGACTTGGATTTTCCAACACAAGTCATCCCATTAAAGACTCTGAATGCAGTTGCTTCAGTACCCATAATGTATTCTTGGTCTCCCCTACAGCAGAATTTTATGGTGGAAGATGAAACTGTTTTACATAACATTCCTTATATGGGAGATGAAGTTTTAGATCAGGATGGTACTTTCATTGAAGAACTAATAAAAAATTATGATGGGAAAGTACACGGGGATAGAGAATGTGGGTTTATAAATGATGAAATTTTTGTGGAGTTGGTGAATGCCCTTGGTCAATATAATGATGATGACGATGATGATGATGGAGACGATCCTGAAGAAAGAGAAGAAAAGCAGAAAGATCTGGAGGATCACCGAGATGATAAAGAAAGCCGCCCACCTCGGAAATTTCCTTCTGATAAAATTTTTGAAGCCATTTCCTCAATGTTTCCAGATAAGGGCACAGCAGAAGAACTAAAGGAAAAATATAAAGAACTCACCGAACAGCAGCTCCCAGGCGCACTTCCTCCTGAATGTACCCCCAACATAGATGGACCAAATGCTAAATCTGTTCAGAGAGAGCAAAGCTTACACTCCTTTCATACGCTTTTCTGTAGGCGATGTTTTAAATATGACTGCTTCCTACATCCTTTTCATGCAACACCCAACACTTATAAGCGGAAGAACACAGAAACAGCTCTAGACAACAAACCTTGTGGACCACAGTGTTACCAGCATTTGGAGGGAGCAAAGGAGTTTGCTGCTGCTCTCACCGCTGAGCGGATAAAGACCCCACCAAAACGTCCAGGAGGCCGCAGAAGAGGACGGCTTCCCAATAACAGTAGCAGGCCCAGCACCCCCACCATTAATGTGCTGGAATCAAAGGATACAGACAGTGATAGGGAAGCAGGGACTGAAACGGGGGGAGAGAACAATGATAAAGAAGAAGAAGAGAAGAAAGATGAAACTTCGAGCTCCTCTGAAGCAAATTCTCGGTGTCAAACACCAATAAAGATGAAGCCAAATATTGAACCTCCTGAGAATGTGGAGTGGAGTGGTGCTGAAGCCTCAATGTTTAGAGTCCTCATTGGCACTTACTATGACAATTTCTGTGCCATTGCTAGGTTAATTGGGACCAAAACATGTAGACAGGTGTATGAGTTTAGAGTCAAAGAATCTAGCATCATAGCTCCAGCTCCCGCTGAGGATGTGGATACTCCTCCAAGGAAAAAGAAGAGGAAACACCGGTTGTGGGCTGCACACTGCAGAAAGATACAGCTGAAAAAGGACGGCTCCTCTAACCATGTTTACAACTATCAACCCTGTGATCATCCACGGCAGCCTTGTGACAGTTCGTGCCCTTGTGTGATAGCACAAAATTTTTGTGAAAAGTTTTGTCAATGTAGTTCAGAGTGTCAAAACCGCTTTCCGGGATGCCGCTGCAAAGCACAGTGCAACACCAAGCAGTGCCCGTGCTACCTGGCTGTCCGAGAGTGTGACCCTGACCTCTGTCTTACTTGTGGAGCCGCTGACCATTGGGACAGTAAAAATGTGTCCTGCAAGAACTGCAGTATTCAGCGGGGCTCCAAAAAGCATCTATTGCTGGCACCATCTGACGTGGCAGGCTGGGGGATTTTTATCAAAGATCCTGTGCAGAAAAATGAATTCATCTCAGAATACTGTGGAGAGATTATTTCTCAAGATGAAGCTGACAGAAGAGGGAAAGTGTATGATAAATACATGTGCAGCTTTCTGTTCAACTTGAACAATGATTTTGTGGTGGATGCAACCCGCAAGGGTAACAAAATTCGTTTTGCAAATCATTCGGTAAATCCAAACTGCTATGCAAAAGTTATGATGGTTAACGGTGATCACAGGATAGGTATTTTTGCCAAGAGAGCCATCCAGACTGGCGAAGAGCTGTTTTTTGATTACAGATACAGCCAGGCTGATGCCCTGAAGTATGTCGGCATCGAAAGAGAAATGGAAATCCCTTGA"
    ),
    # ENST00000613418.4 – used for stop_gained
    "FCGR3B": (
        "ATGCGGACTGAAGATCTCCCAAAGGCTGTGGTGTTCCTGGAGCCTCAATGGTACAGCGTGCTTGAGAAGGACAGTGTGACTCTGAAGTGCCAGGGAGCC"
        "TACTCCCCTGAGGACAATTCCACACAGTGGTTTCACAATGAGAACCTCATCTCAAGCCAGGCCTCGAGCTACTTCATTGACGCTGCCACAGTCAACGAC"
        "AGTGGAGAGTACAGGTGCCAGACAAACCTCTCCACCCTCAGTGACCCGGTGCAGCTAGAAGTCCATATCGGCTGGCTGTTGCTCCAGGCCCCTCGGTGGG"
        "TGTTCAAGGAGGAAGACCCTATTCACCTGAGGTGTCACAGCTGGAAGAACACTGCTCTGCATAAGGTCACATATTTACAGAATGGCAAAGACAGGAAGTAT"
        "TTTCATCATAATTCTGACTTCCACATTCCAAAAGCCACACTCAAAGATAGCGGCTCCTACTTCTGCAGGGGGCTTGTTGGGAGTAAAAATGTGTCTTCAGA"
        "GACTGTGAACATCACCATCACTCAAGGTTTGGCAGTGTCAACCATCTCATCATTCTCTCCACCTGGGTACCAAGTCTCTTTCTGCTTGGTGATGGTACTCC"
        "TTTTTGCAGTGGACACAGGACTATATTTCTCTGTGAAGACAAACATTTGA"
    ),
    # ENST00000646174.1 – used for inframe_deletion
    "CTNNB1": (
        "ATGGAGTTGGACATGGCCATGGAACCAGACAGAAAAGCGGCTGTTAGTCACTGGCAGCAACAGTCTTACCTGGACTCTGGAATCCATTCTGGTGCCACTAC"
        "CACAGCTCCTTCTCTGAGTGGTAAAGGCAATCCTGAGGAAGAGGATGTGGATACCTCCCAAGTCCTGTATGAGTGGGAACAGGGATTTTCTCAGTCCTTCA"
        "CTCAAGAACAAGTAGCTGATATTGATGGACAGTATGCAATGACTCGAGCTCAGAGGGTACGAGCTGCTATGTTCCCTGAGACATTAGATGAGGGCATGCAGA"
        "TCCCATCTACACAGTTTGATGCTGCTCATCCCACTAATGTCCAGCGTTTGGCTGAACCATCACAGATGCTGAAACATGCAGTTGTAAACTTGATTAACTATCA"
        "AGATGATGCAGAACTTGCCACACGTGCAATCCCTGAACTGACAAAACTGCTAAATGACGAGGACCAGGTGGTGGTTAATAAGGCTGCAGTTATGGTCCATCAG"
        "CTTTCTAAAAAGGAAGCTTCCAGACACGCTATCATGCGTTCTCCTCAGATGGTGTCTGCTATTGTACGTACCATGCAGAATACAAATGATGTAGAAACAGCTCG"
        "TTGTACCGCTGGGACCTTGCATAACCTTTCCCATCATCGTGAGGGCTTACTGGCCATCTTTAAGTCTGGAGGCATTCCTGCCCTGGTGAAAATGCTTGGTTCAC"
        "CAGTGGATTCTGTGTTGTTTTATGCCATTACAACTCTCCACAACCTTTTATTACATCAAGAAGGAGCTAAAATGGCAGTGCGTTTAGCTGGTGGGCTGCAGAAAA"
        "TGGTTGCCTTGCTCAACAAAACAAATGTTAAATTCTTGGCTATTACGACAGACTGCCTTCAAATTTTAGCTTATGGCAACCAAGAAAGCAAGCTCATCATACTGG"
        "CTAGTGGTGGACCCCAAGCTTTAGTAAATATAATGAGGACCTATACTTACGAAAAACTACTGTGGACCACAAGCAGAGTGCTGAAGGTGCTATCTGTCTGCTCTA"
        "GTAATAAGCCGGCTATTGTAGAAGCTGGTGGAATGCAAGCTTTAGGACTTCACCTGACAGATCCAAGTCAACGTCTTGTTCAGAACTGTCTTTGGACTCTCAGGA"
        "ATCTTTCAGATGCTGCAACTAAACAGGAAGGGATGGAAGGTCTCCTTGGGACTCTTGTTCAGCTTCTGGGTTCAGATGATATAAATGTGGTCACCTGTGCAGCTG"
        "GAATTCTTTCTAACCTCACTTGCAATAATTATAAGAACAAGATGATGGTCTGCCAAGTGGGTGGTATAGAGGCTCTTGTGCGTACTGTCCTTCGGGCTGGTGACAG"
        "GGAAGACATCACTGAGCCTGCCATCTGTGCTCTTCGTCATCTGACCAGCCGACACCAAGAAGCAGAGATGGCCCAGAATGCAGTTCGCCTTCACTATGGACTACCA"
        "GTTGTGGTTAAGCTCTTACACCCACCATCCCACTGGCCTCTGATAAAGGCTACTGTTGGATTGATTCGAAATCTTGCCCTTTGTCCCGCAAATCATGCACCTTTGC"
        "GTGAGCAGGGTGCCATTCCACGACTAGTTCAGTTGCTTGTTCGTGCACATCAGGATACCCAGCGCCGTACGTCCATGGGTGGGACACAGCAGCAATTTGTGGAGGG"
        "GGTCCGCATGGAAGAAATAGTTGAAGGTTGTACCGGAGCCCTTCACATCCTAGCTCGGGATGTTCACAACCGAATTGTTATCAGAGGACTAAATACCATTCCATTG"
        "TTTGTGCAGCTGCTTTATTCTCCCATTGAAAACATCCAAAGAGTAGCTGCAGGGGTCCTCTGTGAACTTGCTCAGGACAAGGAAGCTGCAGAAGCTATTGAAGCTG"
        "AGGGAGCCACAGCTCCTCTGACAGAGTTACTTCACTCTAGGAATGAAGGTGTGGCGACATATGCAGCTGCTGTTTTGTTCCGAATGTCTGAGGACAAGCCACAAGAT"
        "TACAAGAAACGGCTTTCAGTTGAGCTGACCAGCTCTCTCTTCAGAACAGAGCCAATGGCTTGGAATGAGACTGCTGATCTTGGACTTGATATTGGTGCCCAGGGAGAA"
        "CCCCTTGGATATCGCCAGGATGATCCTAGCTATCGTTCTTTTCACTCTGGTGGATATGGCCAGGATGCCTTGGGTATGGACCCCATGATGGAACATGAGATGGGTGGC"
        "CACCACCCTGGTGCTGACTATCCAGTTGATGGGCTGCCAGATCTGGGGCATGCCCAGGACCTCATGGATGGGCTGCCTCCAGGTGACAGCAATCAGCTGGCCTGGTTT"
        "GATACTGACCTGTAA"
    ),
    # ENST00000370452.7 – used for inframe_insertion (dup)
    "SMAP1": (
        "ATGGCGACGCGCTCCTGTCGGGAGAAGGCTCAGAAGCTGAACGAGCAGCACCAGCTCATCCTATCCAAGCTTCTGAGGGAGGAGGACAACAAGTACTGCGCC"
        "GACTGCGAGGCCAAAGGTCCTCGATGGGCTTCCTGGAATATTGGTGTGTTTATTTGCATCAGATGTGCTGGAATTCATAGAAATCTTGGGGTTCATATATCC"
        "AGGGTCAAATCAGTCAACCTAGACCAATGGACAGCAGAACAGATACAGTGCATGCAAGATATGGGAAATACTAAAGCAAGACTACTCTATGAAGCCAATCTTCC"
        "AGAGAACTTTCGAAGACCACAGACAGATCAAGCAGTGGAATTTTTCATCAGAGATAAATATGAAAAGAAGAAATACTACGATAAAAATGCCATAGCTATTACAAAT"
        "AAAGAAAAGGAAGAAAAAAAAGGAAGAGAAAAAGAGAGAAAAGGAGCCAGAAAAGCCGGCAAAACCACTTACAGCTGAAAAGCTGCAGAAGAAAGATCAGCAACTGG"
        "AGCCTAAAAAAAGTACCAGCCCTAAAAAAGCTGCGGAGCCCACTGTGGATCTTTTAGGACTTGATGGCCCTGCTGTGGCACCAGTGACCAACGGGAACACAACGGTG"
        "CCACCCCTGAACGATGATCTGGACATCTTTGGACCGATGATTTCTAATCCCTTACCTGCAACTGTCATGCCCCCAGCTCAGGGGACACCCTCTGCACCAGCAGCTGCA"
        "ACCCTGTCTACAGTAACATCTGGGGATCTAGATTTATTCACTGAGCAAACTACAAAATCAGAAGAAGTGGCAAAGAAACAACTTTCCAAAGACTCCATCTTATCTCTG"
        "TATGGCACAGGAACCATTCAACAGCAAAGTACTCCTGGTGTATTTATGGGACCCACAAATATACCATTTACCTCACAAGCACCAGCTGCATTTCAGGGCTTTCCATCG"
        "ATGGGCGTGCCTGTGCCTGCAGCTCCTGGCCTTATAGGAAATGTGATGGGACAGAGTCCAAGCATGATGGTGGGCATGCCCATGCCCAATGGGTTTATGGGAAATGCA"
        "CAAACTGGTGTGATGCCACTTCCTCAGAACGTTGTTGGCCCCCAAGGAGGAATGGTGGGACAAATGGGTGCACCCCAGAGTAAGTTTGGCCTGCCGCAAGCTCAGCAG"
        "CCCCAGTGGAGCCTCTCACAGATAATGCAGAAGGGTGATGCTGTTCTCCAGCACTCCATCAGTGCAATCTACTGGCCAATGACAAGGTGGTTAAAATGTCCTTTAGT"
        "AGATGAATCAGCAGATGGCTGGCATGAGTATCAGTAG"
    ),
    # ENST00000361676.8 – used for protein_altering_variant
    "NF2": (
        "ATGGCCGGGGCCATCGCTTCCCGCATGAGCTTCAGCTCTCTCAAGAGGAAGCAACCCAAGACGTTCACCGTGAGGATCGTCACCATGGACGCCGAGATGGAG"
        "TTCAATTGCGAGGTACTGGATCATGATGTTTCAAAGGAAGAACCAGTCACCTTTCACTTCTTGGCCAAATTTTATCCTGAGAATGCTGAAGAGGAGCTGGTT"
        "CAGGAGATCACACAACATTTATTCTTCTTACAGGTAAAGAAGCAGATTTTAGATGAAAAGATCTACTGCCCTCCTGAGGCTTCTGTGCTCCTGGCTTCTTACG"
        "CCGTCCAGGCCAAGTATGGTGACTACGACCCCAGTGTTCACAAGCGGGGATTTTTGGCCCAAGAGGAATTGCTTCCAAAAAGGGTAATAAATCTGTATCAGAT"
        "GACTCCGGAAATGTGGGAGGAGAGAATTACTGCTTGGTACGCAGAGCACCGAGGCCGAGCCAGGGATGAAGCTGAAATGGAATATCTGAAGATAGCTCAGGAC"
        "CTGGAGATGTACGGTGTGAACTACTTTGCAATCCGGAATAAAAAGGGCACAGAGCTGCTGCTTGGAGTGGATGCCCTGGGGCTTCACATTTATGACCCTGAGA"
        "ACAGACTGACCCCCAAGATCTCCTTCCCGTGGAATGAAATCCGAAACATCTCGTACAGTGACAAGGAGTTTACTATTAAACCACTGGATAAGAAAATTGATGTC"
        "TTCAAGTTTAACTCCTCAAAGCTTCGTGTTAATAAGCTGATTCTCCAGCTATGTATCGGGAACCATGATCTATTTATGAGGAGAAGGAAAGCCGATTCTTTGGAA"
        "GTTCAGCAGATGAAAGCCCAGGCCAGGGAGGAGAAGGCTAGAAAGCAGATGGAGCGGCAGCGCCTCGCTCGAGAGAAGCAGATGAGGGAGGAGGCTGAACGCACG"
        "AGGGATGAGTTGGAGAGGAGGCTGCTGCAGATGAAAGAAGAAGCAACAATGGCCAACGAAGCACTGATGCGGTCTGAGGAGACAGCTGACCTGTTGGCTGAAAAG"
        "GCCCAGATCACCGAGGAGGAGGCAAAACTTCTGGCCCAGAAGGCCGCAGAGGCTGAGCAGGAAATGCAGCGCATCAAGGCCACAGCGATTCGCACGGAGGAGGAG"
        "AAGCGCCTGATGGAGCAGAAGGTGCTGGAAGCCGAGGTGCTGGCACTGAAGATGGCTGAGGAGTCAGAGAGGAGGGCCAAAGAGGCAGATCAGCTGAAGCAGGAC"
        "CTGCAGGAAGCACGCGAGGCGGAGCGAAGAGCCAAGCAGAAGCTCCTGGAGATTGCCACCAAGCCCACGTACCCGCCCATGAACCCAATTCCAGCACCGTTGCCTC"
        "CTGACATACCAAGCTTCAACCTCATTGGTGACAGCCTGTCTTTCGACTTCAAAGATACTGACATGAAGCGGCTTTCCATGGAGATAGAGAAAGAAAAAGTGGAATAC"
        "ATGGAAAAGAGCAAGCATCTGCAGGAGCAGCTCAATGAACTCAAGACAGAAATCGAGGCCTTGAAACTGAAAGAGAGGGAGACAGCTCTGGATATTCTGCACAATGA"
        "GAACTCCGACAGGGGTGGCAGCAGCAAGCACAATACCATTAAAAAGCCTCAAGCCCAAGGCAGAAGACCTATCTGCATTTGA"
    ),
    # ENST00000394374.6 – used for frameshift_variant
    "MEN1": (
        "ATGGGGCTGAAGGCCGCCCAGAAGACGCTGTTCCCGCTGCGCTCCATCGACGACGTGGTGCGCCTGTTTGCTGCCGAGCTGGGCCGAGAGGAGCCGGACCTG"
        "GTGCTCCTTTCCTTGGTGCTGGGCTTCGTGGAGCATTTTCTGGCTGTCAACCGCGTCATCCCTACCAACGTTCCCGAGCTCACCTTCCAGCCCAGCCCCGCCC"
        "CCGACCCGCCTGGCGGCCTCACCTACTTTCCCGTGGCCGACCTGTCTATCATCGCCGCCCTCTATGCCCGCTTCACCGCCCAGATCCGAGGCGCCGTCGACCTG"
        "TCCCTCTATCCTCGAGAAGGGGGTGTCTCCAGCCGTGAGCTGGTGAAGAAGGTCTCCGATGTCATATGGAACAGCCTCAGCCGCTCCTACTTCAAGGATCGGGCC"
        "CACATCCAGTCCCTCTTCAGCTTCATCACAGGTTGGAGCCCAGTAGGCACCAAATTGGACAGCTCCGGTGTGGCCTTTGCTGTGGTTGGGGCCTGCCAGGCCCTGG"
        "GTCTCCGGGATGTCCACCTCGCCCTGTCTGAGGATCATGCCTGGGTAGTGTTTGGGCCCAATGGGGAGCAGACAGCTGAGGTCACCTGGCACGGCAAGGGCAACGA"
        "GGACCGCAGGGGCCAGACAGTCAATGCCGGTGTGGCTGAGCGGAGCTGGCTGTACCTGAAAGGATCATACATGCGCTGTGACCGCAAGATGGAGGTGGCGTTCATG"
        "GTGTGTGCCATCAACCCTTCCATTGACCTGCACACCGACTCGCTGGAGCTTCTGCAGCTGCAGCAGAAGCTGCTCTGGCTGCTCTATGACCTGGGACATCTGGAAAG"
        "GTACCCCATGGCCTTAGGGAACCTGGCAGATCTAGAGGAGCTGGAGCCCACCCCTGGCCGGCCAGACCCACTCACCCTCTACCACAAGGGCATTGCCTCAGCCAAGAC"
        "CTACTATCGGGATGAACACATCTACCCCTACATGTACCTGGCTGGCTACCACTGTCGCAACCGCAATGTGCGGGAAGCCCTGCAGGCCTGGGCGGACACGGCCACTGT"
        "CATCCAGGACTACAACTACTGCCGGGAAGACGAGGAGATCTACAAGGAGTTCTTTGAAGTAGCCAATGATGTCATCCCCAACCTGCTGAAGGAGGCAGCCAGCTTGCT"
        "GGAGGCGGGCGAGGAGCGGCCGGGGGAGCAAAGCCAGGGCACCCAGAGCCAAGGTTCCGCCCTCCAGGACCCTGAGTGCTTCGCCCACCTGCTGCGATTCTACGACGG"
        "CATCTGCAAATGGGAGGAGGGCAGTCCCACGCCTGTGCTGCATGTGGGCTGGGCCACCTTTCTTGTGCAGTCCCTAGGCCGTTTTGAGGGACAGGTGCGGCAGAAGGT"
        "GCGCATAGTGAGCCGAGAGGCCGAGGCGGCCGAGGCCGAGGAGCCGTGGGGCGAGGAAGCCCGGGAAGGCCGGCGGCGGGGCCCACGGCGGGAGTCCAAGCCAGAGGAG"
        "CCCCCGCCGCCCAAGAAGCCAGCACTGGACAAGGGCCTGGGCACCGGCCAGGGTGCAGTGTCAGGACCCCCCCGGAAGCCTCCTGGGACTGTCGCTGGCACAGCCCGAGG"
        "CCCTGAAGGTGGCAGCACGGCTCAGGTGCCAGCACCCACAGCATCACCACCGCCGGAGGGTCCAGTGCTCACTTTCCAGAGTGAGAAGATGAAGGGCATGAAGGAGCTGC"
        "TGGTGGCCACCAAGATCAACTCGAGCGCCATCAAGCTGCAACTCACGGCACAGTCGCAAGTGCAGATGAAGAAGCAGAAAGTGTCCACCCCTAGTGACTACACTCTGTCT"
        "TTCCTCAAGCGGCAGCGCAAAGGCCTCTGA"
    ),
    # ENST00000513000.5 – used for start_lost
    "INPP4B": (
        "ATGGAAATTAAAGAGGAAGGGGCATCAGAAGAAGGGCAGCACTTTCTTCCTACAGCCCAGGCCAATGATCCCGGGGACTGTCAGTTCACAAGTATCCAGAAGAC"
        "TCCAAATGAACCGCAGTTGGAATTCATCCTTGCATGCAAGGATCTCGTGGCTCCTGTCCGTGATCGTAAACTGAATACACTGGTGCAGATCTCCGTAATCCACC"
        "CCGTGGAGCAGAGTCTGACAAGATACTCCAGCACCGAAATTGTGGAGGGAACAAGGGACCCACTGTTTTTGACTGGTGTCACATTCCCATCTGAGTATCCCATCT"
        "ATGAGGAGACCAAAATAAAACTAACAGTCTATGATGTCAAGGATAAGTCTCATGACACCGTTCGAACCAGTGTCCTACCAGAACATAAGGATCCCCCGCCAGAAGT"
        "TGGGCGAAGTTTCTTGGGCTATGCCAGTTTTAAAGTGGGAGAGCTGCTGAAGTCAAAGGAGCAATTGCTGGTCCTGAGCCTGAGAACTTCAGATGGTGGCAAAGTG"
        "GTTGGCACCATAGAAGTCAGTGTCGTGAAGATGGGGGAGATTGAGGATGGGGAAGCCGACCACATCACCACAGATGTACAGGGACAAAAGTGTGCCCTGGTATGTGA"
        "ATGTACAGCCCCGGAAAGTGTGAGCGGAAAAGATAACTTACCTTTTTTGAATTCAGTGTTAAAGAACCCAGTATGTAAATTATATAGATTTCCCACATCTGACAATAAG"
        "TGGATGCGAATTCGAGAGCAGATGTCAGAGAGCATTCTTTCCTTTCATATTCCTAAGGAATTGATTTCCCTTCACATTAAAGAAGATTTGTGCAGAAACCAGGAGATA"
        "AAAGAACTTGGTGAGCTTTCTCCACATTGGGACAATCTGCGAAAAAATGTCCTTACTCACTGTGATCAAATGGTGAATATGTACCAAGACATTCTGACAGAACTTAGCA"
        "AGGAAACAGGGTCCTCTTTCAAATCAAGCAGCAGCAAAGGAGAGAAAACATTAGAATTTGTTCCAATAAATCTACATCTGCAAAGAATGCAGGTACACAGCCCTCACTTG"
        "AAAGATGCTCTCTACGATGTCATCACTGTGGGAGCCCCAGCTGCCCATTTTCAGGGATTTAAGAATGGTGGTCTTCGGAAGCTACTCCATAGATTTGAAACAGAAAGAAG"
        "AAATACCGGATACCAGTTTATTTACTATTCACCTGAAAACACAGCCAAAGCAAAGGAAGTTCTCAGCAACATCAATCAACTACAACCTCTTATAGCAACCCATGCAGACC"
        "TACTGCTTAATTCTGCAAGCCAGCATTCTCCAGACAGCTTGAAGAATTCTTTAAAGATGCTTTCAGAAAAAACAGAGCTTTTTGTACATGCCTTCAAGGATCAACTTGTC"
        "AGGAGTGCTCTTTTAGCACTCTACACTGCAAGGCCAGGAGGCATTCTTAAGAAGCCACCCTCTCCTAAGAGCAGCACAGAGGAGAGCAGTCCCCAAGACCAACCCCCAGT"
        "GATGAGAGGGCAGGACTCCATACCACATCATTCAGACTATGATGAGGAAGAGTGGGACAGGGTGTGGGCCAATGTGGGGAAGAGCCTGAACTGCATTATTGCTATGGTGG"
        "ACAAACTGATTGAAAGAGATGGTGGCAGTGAAGGCAGTGGCGGCAACAATGATGGAGAAAAGGAACCTTCATTAACAGATGCCATTCCCTCTCACCCAAGAGAGGACTGG"
        "TATGAACAGTTGTATCCCCTCATCCTTACCCTGAAGGACTGCATGGGAGAAGTGGTGAACCGAGCCAAGCAGTCCCTGACATTTGTGCTCCTTCAGGAACTTGCGTACAGC"
        "TTGCCCCAGTGTCTGATGCTGACGCTAAGAAGAGACATCGTCTTCAGCCAAGCACTTGCTGGATTGGTTTGTGGTTTTATCATCAAATTACAGACAAGTCTGTATGACCC"
        "AGGCTTCCTACAGCAGCTTCACACAGTGGGGTTGATAGTACAATATGAAGGACTGCTAAGTACATACAGCGATGAAATTGGAATGCTAGAGGACATGGCCGTTGGCATTTC"
        "CGATTTAAAGAAAGTTGCATTTAAAATAATTGAAGCCAAATCCAATGATGTGTTGCCAGTTATAACAGGAAGACGAGAACATTACGTGGTAGAGGTCAAGCTTCCAGCCAG"
        "AATGTTTGAGTCACTACCTCTACAGATTAAAGAAGGACAGTTGCTTCATGTGTATCCAGTACTTTTTAATGTTGGAATCAATGAACAGCAAACTCTGGCTGAAAGGTTTGG"
        "AGATGTCTCTTTGCAAGAAAGTATTAATCAGGAAAACTTCGAACTTCTACAAGAATATTACAAGATATTTATGGAAAAGATGCCTCCTGATTATATTTCACATTTTCAGGAA"
        "CAAAATGATTTAAAAGCATTGCTAGAAAATCTCCTTCAAAATATCCAATCCAAAAAAAGAAAGAATGTAGAAATTATGTGGCTGGCTGCAACGATTTGCCGCAAACTGAATG"
        "GTATTCGTTTCACCTGTTGTAAAAGTGCCAAAGACAGGACATCGATGTCAGTGACACTTGAACAATGCTCAATCTTGAGAGATGAGCACCAGTTACACAAGGACTTCTTTAT"
        "CCGAGCGCTGGATTGCATGAGAAGAGAAGGATGCCGCATAGAGAATGTACTGAAGAATATCAAATGCAGAAAGTATGCTTTCAACATGCTACAGCTGATGGCTTTCCCCAAG"
        "TACTACAGACCTCCAGAGGGGACTTATGGAAAAGCTGACACCTAA"
    ),
    # ENST00000443433.6 – used for stop_lost
    "MYD88": (
        "ATGCGACCCGACCGCGCTGAGGCTCCAGGACCGCCCGCCATGGCTGCAGGAGGTCCCGGCGCGGGGTCTGCGGCCCCGGTCTCCTCCACATCCTCCCTTCCCC"
        "TGGCTGCTCTCAACATGCGAGTGCGGCGCCGCCTGTCTCTGTTCTTGAACGTGCGGACACAGGTGGCGGCCGACTGGACCGCGCTGGCGGAGGAGATGGACTTT"
        "GAGTACTTGGAGATCCGGCAACTGGAGACACAAGCGGACCCCACTGGCAGGCTGCTGGACGCCTGGCAGGGACGCCCTGGCGCCTCTGTAGGCCGACTGCTCGAG"
        "CTGCTTACCAAGCTGGGCCGCGACGACGTGCTGCTGGAGCTGGGACCCAGCATTGAGGAGGATTGCCAAAAGTATATCTTGAAGCAGCAGCAGGAGGAGGCTGAG"
        "AAGCCTTTACAGGTGGCCGCTGTAGACAGCAGTGTCCCACGGACAGCAGAGCTGGCGGGCATCACCACACTTGATGACCCCCTGGGTGCCGCCGGATGGTGGTGGT"
        "TGTCTCTGATGATTACCTGCAGAGCAAGGAATGTGACTTCCAGACCAAATTTGCACTCAGCCTCTCTCCAGGTGCCCATCAGAAGCGACTGA"
    ),
    # ENST00000494014.1 – used for stop_retained_variant
    "EPHA3": (
        "ATGGATTGTCAGCTCTCCATCCTCCTCCTTCTCAGCTGCTCTGTTCTCGACAGCTTCGGGGAACTGATTCCGCAGCCTTCCAATGAAGTCAATCTACTGGATTC"
        "AAAAACAATTCAAGGGGAGCTGGGCTGGATCTCTTATCCATCACATGGGTGGGAAGAGATCAGTGGTGTGGATGAACATTACACACCCATCAGGACTTACCAGGTG"
        "TGCAATGTCATGGACCACAGTCAAAACAATTGGCTGAGAACAAACTGGGTCCCCAGGAACTCAGCTCAGAAGATTTATGTGGAGCTCAAGTTCACTCTACGAGACTG"
        "CAATAGCATTCCATTGGTTTTAGGAACTTGCAAGGAGACATTCAACCTGTACTACATGGAGTCTGATGATGATCATGGGGTGAAATTTCGAGAGCATCAGTTTACAAA"
        "GATTGACACCATTGCAGCTGATGAAAGTTTCACTCAAATGGATCTTGGGGACCGTATTCTGAAGCTCAACACTGAGATTAGAGAAGTAGGTCCTGTCAACAAGAAGGG"
        "ATTTTATTTGGCATTTCAAGATGTTGGTGCTTGTGTTGCCTTGGTGTCTGTGAGAGTATACTTCAAAAAGTGCCCATTTACAGTGAAGAATCTGGCTATGTTTCCAGA"
        "CACGGTACCCATGGACTCCCAGTCCCTGGTGGAGGTTAGAGGGTCTTGTGTCAACAATTCTAAGGAGGAAGATCCTCCAAGGATGTACTGCAGTACAGAAGGCGAATGG"
        "CTTGTACCCATTGGCAAGTGTTCCTGCAATGCTGGCTATGAAGAAAGAGGTTTTATGTGCCAAGCTTGTCGACCAGGTTTCTACAAGGCATTGGATGGTAATATGAAGT"
        "GTGCTAAGTGCCCGCCTCACAGTTCTACTCAGGAAGATGGTTCAATGAACTGCAGGTGTGAGAATAATTACTTCCGGGCAGACAAAGACCCTCCATCCATGGCTTGTACC"
        "CGACCTCCATCTTCACCAAGAAATGTTATCTCTAATATAAACGAGACCTCAGTTATCCTGGACTGGAGTTGGCCCCTGGACACAGGAGGCCGGAAAGATGTTACCTTCAAC"
        "ATCATATGTAAAAAATGTGGGTGGAATATAAAACAGTGTGAGCCATGCAGCCCAAATGTCCGCTTCCTCCCTCGACAGTTTGGACTCACCAACACCACGGTGACAGTGACAG"
        "ACCTTCTGGCACATACTAACTACACCTTTGAGATTGATGCCGTTAATGGGGTGTCAGAGCTGAGCTCCCCACCAAGACAGTTTGCTGCGGTCAGCATCACAACTAATCAGGC"
        "TGCTCCATCACCTGTCCTGACGATTAAGAAAGATCGGACCTCCAGAAATAGCATCTCTTTGTCCTGGCAAGAACCTGAACATCCTAATGGGATCATATTGGACTACGAGGTC"
        "AAATACTATGAAAAGCAGGAACAAGAAACAAGTTATACCATTCTGAGGGCAAGAGGCACAAATGTTACCATCAGTAGCCTCAAGCCTGACACTATATACGTATTCCAAATCC"
        "GAGCCCGAACAGCCGCTGGATATGGGACGAACAGCCGCAAGTTTGAGTTTGAAACTAGTCCAGACTCTTTCTCCATCTCTGGTGAAAGTAGCCAAGTGGTCATGATCGCCAT"
        "TTCAGCGGCAGTAGCAATTATTCTCCTCACTGTTGTCATCTATGTTTTGATTGGGAGGTTCTGTGGCTATAAGTCAAAACATGGGGCAGATGAAAAAAGACTTCATTTTGGC"
        "AATGGGCATTTAAAACTTCCAGGTCTCAGGACTTATGTTGACCCACATACATATGAAGACCCTACCCAAGCTGTTCATGAGTTTGCCAAGGAATTGGATGCCACCAACATATC"
        "CATTGATAAAGTTGTTGGAGCAGGTGAATTTGGAGAGGTGTGCAGTGGTCGCTTAAAACTTCCTTCAAAAAAAGAGATTTCAGTGGCCATTAAGACCCTGAAAGTTGGCTAC"
        "ACAGAAAAGCAGAGGAGAGACTTCCTGGGAGAAGCAAGCATTATGGGACAGTTTGACCACCCCAATATCATTCGACTGGAAGGAGTTGTTACCAAAAGTAAGCCAGTTATGA"
        "TTGTCACAGAATACATGGAGAATGGTTCCTTGGATAGTTTCCTACGTAAACACGATGCCCAGTTTACTGTCATTCAGCTAGTGGGGATGCTTCGAGGGATAGCATCTGGCAT"
        "GAAGTACCTGTCAGACATGGGCTATGTTCACCGAGACCTCGCTGCTCGGAACATCTTGATCAACAGTAACTTGGTGTGTAAGGTTTCTGATTTCGGACTTTCGCGTGTCCTG"
        "GAGGATGACCCAGAAGCTGCTTATACAACAAGAGGAGGGAAGATCCCAATCAGGTGGACATCACCAGAAGCTATAGCCTACCGCAAGTTCACGTCAGCCAGCGATGTATGGAG"
        "TTATGGGATTGTTCTCTGGGAGGTGATGTCTTATGGAGAGAGACCATACTGGGAGATGTCCAATCAGGATGTAATTAAAGCTGTAGATGAGGGCTATCGACTGCCACCCCCC"
        "ATGGACTGCCCAGCTGCCTTGTATCAGCTGATGCTGGACTGCTGGCAGAAAGACAGGAACAACAGACCCAAGTTTGAGCAGATTGTTAGTATTCTGGACAAGCTTATCCGGA"
        "ATCCCGGCAGCCTGAAGATCATCACCAGTGCAGCCGCAAGGCCATCAAACCTTCTTCTGGACCAAAGCAATGTGGATATCACTACCTTCCGCACAACAGTGACATGA"
    ),
}


def _seq(gene: str) -> Seq:
    return Seq("".join(_CDS[gene].split()))


def _wt_protein(gene: str) -> str:
    return str(_seq(gene).translate(to_stop=False))


def _call(gene, dna_mut, aa_mut, mutation_type) -> str:
    snp = SNP(gene=gene, mrna="", dna_mut=dna_mut, aa_mut=aa_mut, mutation_type=mutation_type)
    return CancerGenomesService.get_mut_pro_seq(snp, _seq(gene))


# ---------------------------------------------------------------------------
# Actionable types — should produce a non-empty mutant protein
# ---------------------------------------------------------------------------

class TestActionableVariantTypes:

    def test_missense_variant(self):
        """HGVS rule: single AA substitution leaves total protein length unchanged.

        Source: EZH2 c.656C>T p.S219F (missense_variant)
        DNA path: substitution at position 656 (C→T) changes codon 219 from Ser to Phe.
        """
        wt = _wt_protein("EZH2")
        result = _call("EZH2", "c.656C>T", "p.S219F", "missense_variant")

        assert result, "missense_variant must produce a non-empty protein"
        assert len(result) == len(wt), (
            f"Missense must preserve protein length: wt={len(wt)}, mut={len(result)}"
        )
        assert result[218] == "F", (
            f"Position 219 (index 218) must change to Phe; got '{result[218]}'"
        )
        assert result[:218] == wt[:218], "Residues before the substitution must be unchanged"
        assert result[219:] == wt[219:], "Residues after the substitution must be unchanged"

    def test_stop_gained(self):
        """HGVS rule: stop codon (*) introduced at the predicted position.

        Source: FCGR3B c.394A>T p.K132* (stop_gained)
        DNA path: substitution at position 394 (A→T) converts codon 132 to a stop.
        """
        result = _call("FCGR3B", "c.394A>T", "p.K132*", "stop_gained")

        assert result, "stop_gained must produce a non-empty translated sequence"
        assert result[131] == "*", (
            f"Stop codon must be introduced at position 132 (index 131); got '{result[131]}'"
        )

    def test_inframe_deletion(self):
        """HGVS rule: in-frame deletion shortens the protein by exactly the number of deleted codons.

        Source: CTNNB1 c.104_124del p.T35_G41del (inframe_deletion)
        DNA path: deletes 21 nucleotides (positions 104–124) = 7 codons = 7 amino acids.
        """
        wt = _wt_protein("CTNNB1")
        result = _call("CTNNB1", "c.104_124del", "p.T35_G41del", "inframe_deletion")

        deleted_nt = 124 - 104 + 1   # 21 nt = 7 codons
        deleted_aa = deleted_nt // 3

        assert result, "inframe_deletion must produce a non-empty protein"
        assert len(result) == len(wt) - deleted_aa, (
            f"Inframe deletion of {deleted_aa} AAs: expected len {len(wt) - deleted_aa}, "
            f"got {len(result)}"
        )
        assert result[:34] == wt[:34], "Residues before the deletion must be unchanged"

    def test_inframe_insertion_dup(self):
        """HGVS rule: in-frame duplication lengthens the protein by exactly the number of duplicated codons.

        Source: SMAP1 c.1226_1228dup p.I409dup (inframe_insertion)
        DNA path: duplicates 3 nucleotides (positions 1226–1228) = 1 codon = 1 amino acid inserted.
        """
        wt = _wt_protein("SMAP1")
        result = _call("SMAP1", "c.1226_1228dup", "p.I409dup", "inframe_insertion")

        inserted_nt = 1228 - 1226 + 1   # 3 nt = 1 codon
        inserted_aa = inserted_nt // 3

        assert result, "inframe_insertion (dup) must produce a non-empty protein"
        assert len(result) == len(wt) + inserted_aa, (
            f"Duplication of {inserted_aa} AA: expected len {len(wt) + inserted_aa}, "
            f"got {len(result)}"
        )
        assert result[:409] == wt[:409], "Residues before the duplication site must be unchanged"

    def test_protein_altering_variant(self):
        """HGVS rule: delins replaces a nucleotide range; result is non-empty and differs from WT.

        Source: NF2 c.252_262delinsCT p.L85_K88delins* (protein_altering_variant)
        DNA path: deletes positions 252–262 (11 nt) and inserts CT (2 nt).
        The AA annotation (delins*) predicts a premature stop in the altered sequence.
        """
        wt = _wt_protein("NF2")
        result = _call("NF2", "c.252_262delinsCT", "p.L85_K88delins*", "protein_altering_variant")

        assert result, "protein_altering_variant must produce a non-empty sequence"
        assert result != wt, "protein_altering_variant must differ from the wild-type sequence"

    def test_frameshift_variant(self):
        """HGVS rule: out-of-frame deletion disrupts the reading frame; the code translates the
        resulting sequence as-is (to_stop=False) producing a non-empty aberrant protein.

        Source: MEN1 c.292del p.R98Efs*21 (frameshift_variant)
        DNA path: single-nucleotide deletion at position 292 shifts the reading frame.
        """
        result = _call("MEN1", "c.292del", "p.R98Efs*21", "frameshift_variant")

        assert result, "frameshift_variant must produce a non-empty translated sequence"

    def test_start_lost(self):
        """HGVS rule: start codon destroyed; the processed sequence no longer begins with Met.

        Source: INPP4B c.3G>T p.M1? (start_lost)
        The annotation is p.M1? (ambiguous protein consequence) but dna_mut is unambiguous,
        so the DNA substitution path is taken.  ATG (Met) → ATT (Ile) at codon 1.
        """
        result = _call("INPP4B", "c.3G>T", "p.M1?", "start_lost")

        assert result, "start_lost must produce a non-empty translated sequence via the DNA path"
        assert result[0] != "M", "Start codon is destroyed; first AA must no longer be Met"
        assert result[0] == "I", "ATG→ATT encodes Ile; first AA must be Ile"

    def test_stop_lost(self):
        """HGVS rule: stop codon removed; the protein extends past the original terminus.

        Source: MYD88 c.611_613delinsGCGGCCCCC p.D204_*205delinsGGPR (protein_altering_variant,stop_lost)
        DNA path: delins at 611–613 removes the original stop codon; the protein extends.
        """
        wt = _wt_protein("MYD88")
        result = _call(
            "MYD88",
            "c.611_613delinsGCGGCCCCC",
            "p.D204_*205delinsGGPR",
            "protein_altering_variant,stop_lost",
        )

        assert result, "stop_lost must produce a non-empty protein"
        assert len(result) > len(wt), (
            f"Stop-lost protein must be longer than WT: wt={len(wt)}, mut={len(result)}"
        )

    def test_stop_retained_variant(self):
        """HGVS rule: synonymous change at the stop codon; stop is preserved; length unchanged.

        Source: EPHA3 c.2756G>A p.*919= (stop_retained_variant)
        DNA path: TGA (stop) → TAA (stop); both are stop codons, protein length is unchanged.
        """
        wt = _wt_protein("EPHA3")
        result = _call("EPHA3", "c.2756G>A", "p.*919=", "stop_retained_variant")

        assert result, "stop_retained_variant must produce a non-empty sequence"
        assert len(result) == len(wt), (
            f"Stop-retained must preserve protein length: wt={len(wt)}, mut={len(result)}"
        )
        assert result[-1] == "*", "Stop codon must still be present at the terminus"


# ---------------------------------------------------------------------------
# Filtered / skipped types — get_mut_pro_seq must return an empty string
# ---------------------------------------------------------------------------

class TestSkippedVariantTypes:

    def test_synonymous_variant_is_prefiltered(self):
        """synonymous_variant rows are discarded in cosmic_to_proteindb before get_mut_pro_seq
        is ever called.  Verify the filter expression matches the v103 SO term.
        """
        assert "synonymous_variant" in "synonymous_variant"
        assert "synonymous_variant" in "splice_region_variant,synonymous_variant"
        assert "synonymous_variant" not in "missense_variant"

    def test_intron_variant_returns_empty(self):
        """intron_variant always carries p.? — the p.? guard returns an empty string.

        Source: RAD51C c.145+706C>T p.? (intron_variant)
        """
        result = _call("EZH2", "c.145+706C>T", "p.?", "intron_variant")
        assert result == "", f"intron_variant with p.? must return ''; got {repr(result)}"

    def test_3_prime_utr_variant_returns_empty(self):
        """3_prime_UTR_variant always carries p.? — the p.? guard returns an empty string.

        Source: SUFU c.*2816G>A p.? (3_prime_UTR_variant)
        The c.*N notation signals a 3'UTR position; the outer if-condition fails on p.?.
        """
        result = _call("EZH2", "c.*2816G>A", "p.?", "3_prime_UTR_variant")
        assert result == "", f"3_prime_UTR_variant with p.? must return ''; got {repr(result)}"

    def test_5_prime_utr_variant_returns_empty(self):
        """5_prime_UTR_variant always carries p.? — the p.? guard returns an empty string.

        Source: PSMD13 c.-20C>T p.? (5_prime_UTR_variant)
        """
        result = _call("EZH2", "c.-20C>T", "p.?", "5_prime_UTR_variant")
        assert result == "", f"5_prime_UTR_variant with p.? must return ''; got {repr(result)}"

    def test_coding_sequence_variant_returns_empty(self):
        """coding_sequence_variant in v103 uses intronic-offset positions with p.?.

        Source: OAS2 c.2157+2A>G p.? (coding_sequence_variant)
        Both the intronic offset guard ('+' in coord) and the p.? guard ensure ''.
        """
        result = _call("EZH2", "c.2157+2A>G", "p.?", "coding_sequence_variant")
        assert result == "", f"coding_sequence_variant with p.? must return ''; got {repr(result)}"

    def test_splice_acceptor_variant_returns_empty(self):
        """splice_acceptor_variant uses intronic-offset position notation with p.?.

        Source: TSHR c.171-1G>A p.? (splice_acceptor_variant)
        The '-' offset guard in the delins branch (and p.? in the substitution guard) return ''.
        """
        result = _call("EZH2", "c.171-1G>A", "p.?", "splice_acceptor_variant")
        assert result == "", f"splice_acceptor_variant with p.? must return ''; got {repr(result)}"

    def test_splice_donor_variant_returns_empty(self):
        """splice_donor_variant uses downstream-offset position notation with p.?.

        Source: PTCH1 c.3306+2T>G p.? (splice_donor_variant)
        """
        result = _call("EZH2", "c.3306+2T>G", "p.?", "splice_donor_variant")
        assert result == "", f"splice_donor_variant with p.? must return ''; got {repr(result)}"

    def test_splice_region_variant_composite_treated_as_primary_type(self):
        """splice_region_variant only appears in v103 as part of a composite type string.
        When combined with missense_variant, the missense guard fires first and the
        mutation is processed as a missense — same-length result with a single AA change.

        Source: EZH2 c.656C>T p.S219F (missense_variant — re-used with composite type)
        """
        wt = _wt_protein("EZH2")
        result = _call(
            "EZH2", "c.656C>T", "p.S219F", "missense_variant,splice_region_variant"
        )
        assert result, "composite type containing missense_variant must produce a result"
        assert len(result) == len(wt), "missense-handled result must preserve protein length"
        assert result[218] == "F", "Substitution at codon 219 must produce Phe"

    def test_incomplete_terminal_codon_variant_returns_empty(self):
        """incomplete_terminal_codon_variant is absent from v103 targeted-screen data.
        By convention it carries p.?, so get_mut_pro_seq returns an empty string.
        """
        result = _call("EZH2", "c.2213_2214insA", "p.?", "incomplete_terminal_codon_variant")
        assert result == "", (
            f"incomplete_terminal_codon_variant with p.? must return ''; got {repr(result)}"
        )
